version: "3.1"

services:
  mongo:
    image: mongo:4.2.1
    hostname: mongo
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: arkhn
      MONGO_INITDB_ROOT_PASSWORD: SuperSecurePassword2019
      MONGO_INITDB_DATABASE: fhirstore
    ports:
      - 27017:27017
    volumes:
      - fhirstore-db:/data/db
    command: --replSet rs0

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.1
    container_name: elasticsearch
    environment:
      ELASTIC_PASSWORD: SuperSecurePassword2019
      http.port: 9200
      http.cors.enabled: "true"
      http.cors.allow-origin: "*"
      http.cors.allow-headers: X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization
      http.cors.allow-credentials: "true"
    ports:
      - 9200:9200
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - esdata:/usr/share/elasticsearch/data

  monstache:
    image: arkhn/monstache:6.6.0
    container_name: monstache
    command: -f /opt/monstache.toml -mapper-plugin-path /lib/fhirstore_map_documents.so
    restart: always
    volumes:
      - ./monstache.toml:/opt/monstache.toml
    depends_on:
      - mongo
      - elasticsearch

  dejavu:
    image: appbaseio/dejavu
    container_name: dejavu
    depends_on:
      - elasticsearch
    ports:
      - 1358:1358

volumes:
  fhirstore-db:
    driver: local
  esdata:
    driver: local
